name: GitHub Cleanup

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
  workflow_dispatch:
  # every day at 9:OO
  schedule:
    - cron: "0 9 * * *"

jobs:
  cleanup:
    name: GitHub Cleanup
    uses: nikhilbadyal/ghactions/.github/workflows/github-cleanup.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
